'use client';
import {useState} from 'react';
const euro=n=>(n/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const initial=[{id:1042,ref:'Bestellung #1042',customer:'@lena',gross:7990,fee:140,status:'Bezahlt'},{id:1041,ref:'Bestellung #1041',customer:'@max',gross:4590,fee:89,status:'Bezahlt'},{id:1040,ref:'Bestellung #1040',customer:'@sophie',gross:12900,fee:214,status:'Bezahlt'}];
export default function Home(){
 const [tab,setTab]=useState('merchant'),[tx,setTx]=useState(initial),[paid,setPaid]=useState(5000),[notice,setNotice]=useState(''),[wallet,setWallet]=useState(124850);
 const gross=tx.reduce((s,x)=>s+x.gross,0),fees=tx.filter(x=>x.status!=='Refund').reduce((s,x)=>s+x.fee,0),refunds=tx.filter(x=>x.status==='Refund').reduce((s,x)=>s+x.gross,0),available=Math.max(0,gross-fees-refunds-paid);
 const toast=m=>{setNotice(m);setTimeout(()=>setNotice(''),1800)};
 const refund=id=>{setTx(tx.map(x=>x.id===id&&x.status!=='Refund'?{...x,status:'Refund'}:x));toast('Refund in der Sandbox verbucht')};
 const payout=()=>{if(available){setPaid(paid+available);toast('Sandbox-Auszahlung markiert')}};
 const pay=()=>{setWallet(wallet-1250);toast('12,50 € Sandbox-Zahlung gesendet')};
 return <main className="shell">{notice&&<div className="toast">{notice}</div>}<header><div><span className="eyebrow">PROJECT M · MVP SANDBOX</span><h1>{tab==='merchant'?'Studio Müller':'@ronny'}</h1></div><button className="avatar" onClick={()=>setTab(tab==='merchant'?'wallet':'merchant')}>RM</button></header><nav><button className={tab==='merchant'?'active':''} onClick={()=>setTab('merchant')}>Business</button><button className={tab==='wallet'?'active':''} onClick={()=>setTab('wallet')}>Wallet</button></nav>
 {tab==='merchant'?<><section className="hero"><span>Verfügbar zur Auszahlung</span><strong>{euro(available)}</strong><button onClick={payout}>Auf Geschäftskonto auszahlen</button><small>Sandbox · keine echte Banküberweisung</small></section><section className="stats"><div><span>Umsatz</span><b>{euro(gross)}</b></div><div><span>Gebühren</span><b>{euro(fees)}</b></div><div><span>Refunds</span><b>{euro(refunds)}</b></div></section><section><h2>Zahlungen</h2>{tx.map(x=><article className="row" key={x.id}><div><b>{x.ref}</b><span>{x.customer} · {x.status}</span></div><div className="right"><b>{euro(x.gross)}</b>{x.status!=='Refund'&&<button className="link" onClick={()=>refund(x.id)}>Refund</button>}</div></article>)}</section></>:<><section className="hero"><span>Wallet</span><strong>{euro(wallet)}</strong><button onClick={pay}>Pay 12,50 €</button></section><section className="idcard"><div><b>@ronny</b><span>QR · Link · Checkout</span></div><div className="qr">M</div></section></>}
 <footer><b>Project M</b><span>Produktdemo · kein Echtgeld</span></footer></main>}