'use client';
import {useState} from 'react';
const euro=n=>(n/100).toLocaleString('de-DE',{style:'currency',currency:'EUR'});
const initial=[{id:1042,ref:'Bestellung #1042',customer:'@lena',gross:7990,fee:140,status:'Bezahlt'},{id:1041,ref:'Bestellung #1041',customer:'@max',gross:4590,fee:89,status:'Bezahlt'},{id:1040,ref:'Bestellung #1040',customer:'@sophie',gross:12900,fee:214,status:'Bezahlt'}];
export default function Home(){
 const [tab,setTab]=useState('merchant'),[tx,setTx]=useState(initial),[paid,setPaid]=useState(5000),[notice,setNotice]=useState(''),[wallet,setWallet]=useState(124850),[recipient,setRecipient]=useState('@lena'),[amount,setAmount]=useState('12,50'),[history,setHistory]=useState([]);
 const gross=tx.reduce((s,x)=>s+x.gross,0),fees=tx.filter(x=>x.status!=='Refund').reduce((s,x)=>s+x.fee,0),refunds=tx.filter(x=>x.status==='Refund').reduce((s,x)=>s+x.gross,0),available=Math.max(0,gross-fees-refunds-paid);
 const toast=m=>{setNotice(m);setTimeout(()=>setNotice(''),2200)};
 const refund=id=>{setTx(tx.map(x=>x.id===id&&x.status!=='Refund'?{...x,status:'Refund'}:x));toast('Refund in der Sandbox verbucht')};
 const payout=()=>{if(available){setPaid(paid+available);toast('Sandbox-Auszahlung markiert')}};
 const send=()=>{let cents=Math.round(Number(amount.replace(',','.'))*100);let to=recipient.trim();if(!to.startsWith('@')||to.length<2)return toast('Bitte einen @Namen eingeben');if(!cents||cents<1)return toast('Bitte einen gültigen Betrag eingeben');if(cents>wallet)return toast('Nicht genug Sandbox-Guthaben');setWallet(wallet-cents);setHistory([{id:Date.now(),to,amount:cents},...history]);toast(euro(cents)+' an '+to+' gesendet')};
 return <main className="shell">{notice&&<div className="toast">{notice}</div>}<header><div><span className="eyebrow">PROJECT M · MVP SANDBOX</span><h1>{tab==='merchant'?'Studio Müller':'@ronny'}</h1></div><button className="avatar" onClick={()=>setTab(tab==='merchant'?'wallet':'merchant')}>RM</button></header><nav><button className={tab==='merchant'?'active':''} onClick={()=>setTab('merchant')}>Business</button><button className={tab==='wallet'?'active':''} onClick={()=>setTab('wallet')}>Wallet</button></nav>
 {tab==='merchant'?<><section className="hero"><span>Verfügbar zur Auszahlung</span><strong>{euro(available)}</strong><button onClick={payout}>Auf Geschäftskonto auszahlen</button><small>Sandbox · keine echte Banküberweisung</small></section><section className="stats"><div><span>Umsatz</span><b>{euro(gross)}</b></div><div><span>Gebühren</span><b>{euro(fees)}</b></div><div><span>Refunds</span><b>{euro(refunds)}</b></div></section><section><h2>Zahlungen</h2>{tx.map(x=><article className="row" key={x.id}><div><b>{x.ref}</b><span>{x.customer} · {x.status}</span></div><div className="right"><b>{euro(x.gross)}</b>{x.status!=='Refund'&&<button className="link" onClick={()=>refund(x.id)}>Refund</button>}</div></article>)}</section></>:<><section className="hero"><span>Wallet</span><strong>{euro(wallet)}</strong><small>Sandbox · kein Echtgeld</small></section><section className="idcard"><div><b>@ronny</b><span>Deine Project-M-ID</span></div><div className="qr">M</div></section><section><h2>Geld senden</h2><div className="sendbox"><label>Empfänger</label><input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="@name"/><label>Betrag in €</label><input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="12,50"/><button onClick={send}>Senden</button></div>{history.length>0&&<><h2>Letzte Sendungen</h2>{history.map(x=><article className="row" key={x.id}><div><b>{x.to}</b><span>Sandbox · Gesendet</span></div><div className="right"><b>-{euro(x.amount)}</b></div></article>)}</>}</section></>}
 <footer><b>Project M</b><span>Produktdemo · kein Echtgeld</span></footer></main>}